[book]
authors = ["ismantic-dev"]
language = "zh-CN"
src = "."
title = "底层实现"
description = "语言技术基础导论"

[build]
build-dir = "../book-new"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = true
no-section-label = true
