[book]
authors = ["ismantic-dev"]
language = "zh-CN"
src = "."
title = "底层实现：编译器"
description = "从 AST、Visitor 到运行时对象、容器与 FFI 的编译器实现"

[build]
build-dir = "../book-matx"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = true
no-section-label = true
